import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import Masonry, { ResponsiveMasonry } from "react-responsive-masonry";


import Card from "../components/Card";
import styles from "../styles/Home.module.css";
import { key } from "../api.json";



export default function Home() {
  const [pictures, setPictures] = useState([]);
  function getData() {
    axios.get(`https://api.nasa.gov/planetary/apod?count=6&thumbs=True&api_key=${key}`).then(res => {
      setPictures([...pictures, ...res.data]);
    });
  }

  useEffect((getData), []);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Cosmos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ResponsiveMasonry columnsCountBreakPoints={{ 350: 1, 750: 2}}>
        <Masonry gutter="1rem">
          {pictures.map((pictures) => (
            <Card data={pictures} key={pictures.date}/>
          ))}
        </Masonry>
      </ResponsiveMasonry>
      <button onClick={getData}>Load More</button>
    </div>
  );
}

// export const getStaticProps = async () => {
//   const res = await fetch(
//     `https://api.nasa.gov/planetary/apod?count=100&thumbs=True&api_key=${key}`
//   );
//   const pictures = (await res.json()).reverse();

//   return {
//     props: {
//       pictures,
//     },
//   };
// };
